USE [master]
GO

/****** Object:  Database [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF]    Script Date: 15.02.2019 0:13:00 ******/
CREATE DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'University', FILENAME = N'A:\Учеба\ADO.NET\HomeWork\ADO.NET_HW1\ADO.NET_HW1\App_Data\University.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'University_log', FILENAME = N'A:\Учеба\ADO.NET\HomeWork\ADO.NET_HW1\ADO.NET_HW1\App_Data\University_log.ldf' , SIZE = 768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ANSI_NULLS ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ANSI_PADDING ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ARITHABORT ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET QUERY_STORE = OFF
GO

ALTER DATABASE [A:\УЧЕБА\ADO.NET\HOMEWORK\ADO.NET_HW1\ADO.NET_HW1\APP_DATA\UNIVERSITY.MDF] SET  READ_WRITE 
GO

